
atoms:
  application: aa
  broadcast:
    type: redis
    channel: testch
    broadcastConfig:
      #host: 192.168.1.85
      host: 127.0.0.1
      port: 6379
      usePool: true
      timeout: 0
    lstBroadset:
     - region: hello
       key: ddd
     - region: jregion
       key: jkey
  serializer:
    type: fst
  cache:
   - level: 1
     type: ehcache
     cacheTTL:
        lstTTL:
         - name: hello
           value: 100000000
           broadset: false
     cacheConfig:
       configFile: ehcache.xml


   - level: 2
     type: redis
     cacheConfig:
       #host: 192.168.1.85
       host: 127.0.0.1
       port: 6379
       timeout: 2000
       database: 15
       namespace: atoms
       maxTotal: -1
       maxIdle: 2000
       maxWaitMillis: 100
       minEvictableIdleTimeMillis: 864000000
       minIdle: 100
       numTestsPerEvictionRun: 10
       lifo: false
       softMinEvictableIdleTimeMillis: 10
       testOnBorrow: true
       testOnReturn: false
       testWhileIdle: false
       timeBetweenEvictionRunsMillis: 300000
       blockWhenExhausted: true
server:
  port: 8099
  display-name: atoms



